version: "3.8"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  redis_data: {}

services:
  postgres:
    image: postgres:12.3
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    restart: on-failure
    env_file:
      - ./conf/env/postgres
  redis:
    image: "redis:alpine"
  django:
    build:
      context: .
      dockerfile: ./conf/compose/django/Dockerfile
    image: url_shortener_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
    env_file:
      - ./conf/env/django
      - ./conf/env/postgres
    ports:
      - "8000:8000"
    restart: on-failure
    command: /start
  celery:
    build:
      context: .
      dockerfile: ./conf/compose/django/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - ./api:/app
    env_file:
      - ./conf/env/django
      - ./conf/env/postgres
    depends_on:
      - postgres
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: ./conf/compose/django/Dockerfile
    command: celery -A config beat -l info
    volumes:
      - ./api:/app
    env_file:
      - ./conf/env/django
      - ./conf/env/postgres
    depends_on:
      - postgres
      - redis
